#!/usr/bin/env python3
"""Generate ledmap.c from rgb_layers.csv.

Run this after editing rgb_layers.csv, then commit the regenerated ledmap.c
alongside it -- the firmware build itself stays fully static (no Python at
build time).
"""
import csv
import pathlib

HERE = pathlib.Path(__file__).parent
CSV_PATH = HERE / "rgb_layers.csv"
OUT_PATH = HERE / "ledmap.c"

LAYER_COUNT = 8
LED_COUNT = 54

# Transcribed from this keymap's halcyon_overrides.c g_led_config.matrix_co.
# A hardware fact of the PCB -- only needs updating if that table ever changes.
ROW_COL_TO_LED = [
    [24, 23, 22, 21, 20, 19],
    [25, 18, 17, 16, 15, 14],
    [26, 13, 12, 11, 10, 9],
    [None, None, None, 8, 7, 6],
    [None, None, None, None, None, None],
    [51, 50, 49, 48, 47, 46],
    [52, 45, 44, 43, 42, 41],
    [53, 40, 39, 38, 37, 36],
    [None, None, None, 35, 34, 33],
    [None, None, None, None, None, None],
]


def parse_int_or_star(value):
    return None if value.strip() == "*" else int(value)


def load_rows():
    with open(CSV_PATH, newline="") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("layer,"):
                continue
            layer_s, row_s, col_s, h_s, s_s, v_s = next(csv.reader([line]))
            yield (
                int(layer_s),
                parse_int_or_star(row_s),
                parse_int_or_star(col_s),
                int(h_s),
                int(s_s),
                int(v_s),
            )


def set_led(ledmap, layer, row, col, hsv):
    led = ROW_COL_TO_LED[row][col]
    if led is not None:
        ledmap[layer][led] = hsv


def build_ledmap():
    ledmap = [[(0, 0, 0)] * LED_COUNT for _ in range(LAYER_COUNT)]
    for layer, row, col, h, s, v in load_rows():
        hsv = (h, s, v)
        rows = range(10) if row is None else [row]
        cols = range(6) if col is None else [col]
        for r in rows:
            for c in cols:
                set_led(ledmap, layer, r, c, hsv)
    return ledmap


def format_layer(triplets):
    return ", ".join(f"{{{h}, {s}, {v}}}" for h, s, v in triplets)


def main():
    ledmap = build_ledmap()
    layer_lines = "\n".join(
        f"    [{i}] = {{ {format_layer(triplets)} }},"
        for i, triplets in enumerate(ledmap)
    )

    output = f"""// GENERATED FILE -- do not edit directly.
// Generated by generate_ledmap.py from rgb_layers.csv. Edit that file and
// regenerate (`python3 generate_ledmap.py`) instead of hand-editing this one.

#ifdef RGB_MATRIX_ENABLE
#include QMK_KEYBOARD_H

extern rgb_config_t rgb_matrix_config;

static const uint8_t PROGMEM ledmap[][RGB_MATRIX_LED_COUNT][3] = {{
{layer_lines}
}};

static RGB hsv_to_rgb_with_value(HSV hsv) {{
    RGB   rgb = hsv_to_rgb(hsv);
    float f   = (float)rgb_matrix_config.hsv.v / UINT8_MAX;
    return (RGB){{f * rgb.r, f * rgb.g, f * rgb.b}};
}}

static void set_layer_color(uint8_t layer) {{
    for (uint8_t i = 0; i < RGB_MATRIX_LED_COUNT; i++) {{
        HSV hsv = {{
            .h = pgm_read_byte(&ledmap[layer][i][0]),
            .s = pgm_read_byte(&ledmap[layer][i][1]),
            .v = pgm_read_byte(&ledmap[layer][i][2]),
        }};
        if (!hsv.h && !hsv.s && !hsv.v) {{
            rgb_matrix_set_color(i, 0, 0, 0);
        }} else {{
            RGB rgb = hsv_to_rgb_with_value(hsv);
            rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
        }}
    }}
}}

bool rgb_matrix_indicators_user(void) {{
    uint8_t layer = get_highest_layer(layer_state);
    if (layer < {LAYER_COUNT}) {{
        set_layer_color(layer);
    }} else {{
        rgb_matrix_set_color_all(0, 0, 0);
    }}
    return true;
}}
#endif
"""
    OUT_PATH.write_text(output)
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
